http_port: 8080
login: false
    
photo:
  projects:

  - project: myproject
    root_path: 'photo_meta'
    root_data_path: 'photo_data'
    classification_definition_csv: photo_classification_definitions.csv
    review_list_path: 'photo_review_lists'